# Generated by Django 4.2.14 on 2024-08-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
