# Generated by Django 4.2.14 on 2024-08-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quot_app', '0002_remove_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bankdetails',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='termsConditions',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
